Do not configure WSUS to require SSL from some connections
After configuring WSUS to require SSL from some connections, a number of errors occurred with the WSUS "health check", specifically:

Source: Windows Server Update Services
Event ID: 12002
Event Category: 9
User: N/A
Computer: TT-WSUS03.corp.technologytoolbox.com
Event Description: The Reporting Web Service is not working.

 Source: Windows Server Update Services
Event ID: 12012
Event Category: 9
User: N/A
Computer: TT-WSUS03.corp.technologytoolbox.com
Event Description: The API Remoting Web Service is not working.

Source: Windows Server Update Services
Event ID: 12022
Event Category: 9
User: N/A
Computer: TT-WSUS03.corp.technologytoolbox.com
Event Description: The Client Web Service is not working.

Source: Windows Server Update Services
Event ID: 12032
Event Category: 9
User: N/A
Computer: TT-WSUS03.corp.technologytoolbox.com
Event Description: The Server Synchronization Web Service is not working.

Source: Windows Server Update Services
Event ID: 12042
Event Category: 9
User: N/A
Computer: TT-WSUS03.corp.technologytoolbox.com
Event Description: The SimpleAuth Web Service is not working.

Source: Windows Server Update Services
Event ID: 12052
Event Category: 9
User: N/A
Computer: TT-WSUS03.corp.technologytoolbox.com
Event Description: The DSS Authentication Web Service is not working.

Source: Windows Server Update Services
Event ID: 12072
Event Category: 9
User: N/A
Computer: TT-WSUS03.corp.technologytoolbox.com
Event Description: The WSUS content directory is not accessible.
System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.UpdateServices.Internal.HealthMonitoring.HmtWebServices.CheckContentDirWebAccess(EventLoggingType type, HealthEventLogger logger)

Source: Windows Server Update Services
Event ID: 13042
Event Category: 6
User: N/A
Computer: TT-WSUS03.corp.technologytoolbox.com
Event Description: Self-update is not working.

I attempted several fixes to resolve the errors:

- Adding "wsus.technologytoolbox.com" to BackConnectionHostnames (as suggested by https://social.technet.microsoft.com/Forums/en-US/bdfd9115-856c-45b1-9749-109eeb60c396/many-errors-after-installing-wsus-1201212032-1202212052?forum=winserverwsus)
- Modifying the "https" site binding in IIS to specify a host name (both with and without the "Require Server Name Indication" option)
- Manually setting the "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Update Services\Server\Setup\HostHeader" registry value to "wsus.technologytoolbox.com"

However, none of these changes resolved the errors.